### ISSUE TITLE
FIFO is written even when full flag is asserted

### ISSUE THREAD

**Issue by TeresaReLo** [TeresaReLo/FIFO_Memory_Formal#1]
According to the design specifications: when writeEn is asserted (set to 1) and the FIFO is not full (full is 0), the data present on writeData is written into the memory array in one clock cycle at the location indicated by wrPtr but what we see in the simulation is that a write operation happens when the full flag is active.

![Capture](https://github.com/TeresaReLo/FIFO_Memory_Formal/assets/133064673/72520ba9-6815-4691-8ee9-7f9149240333)

I also add the JasperGold waveform when the assertion fails, we can see that when the writeEn is off, the memory writes a value in mem[0] which should not happen since we are expecting the data maintains stable until one clock cycle after the writeEn is active.

![assertion20](https://github.com/TeresaReLo/FIFO_Memory_Formal/assets/133064673/e495fa02-71eb-40fa-a4a9-8f0a319e0ff1)

**Comment by ana-pgodoy** [comment]
Hello, I already solved that problem in the rtl design. 
In the following screenshot you can see that although the writeEn signal is asserted while the memory is full, both the wrPtr and the memory remain stable so no writing is being done. In the other case, when the writeEn is asserted and full at low we can observe the writing on the next posedge.
We can also observe how the full flag falls when there is a read and then rises again when there is another write.

![Screenshot from 2024-06-10 09-56-52](https://github.com/TeresaReLo/FIFO_Memory_Formal/assets/131797963/a801d52f-0c8b-429a-884a-b2b7d97fa153)

After fixing this problem, I noticed the same situation for the empty flag and the read, so that was fixed as well. Attached is the screenshot of the read operation and the behavior of the memory while the empty flag is asserted.

![Screenshot from 2024-06-10 09-22-02](https://github.com/TeresaReLo/FIFO_Memory_Formal/assets/131797963/858a8efe-d049-4e37-9d2b-cf743463efcd)

**Comment by TeresaReLo** [comment]
Hi, I already proved the fix that you provided, and it works, but just for the record, I add to the precondition of the assertion the flag so that way we ensure that the data is stable also after reset.

![5](https://github.com/TeresaReLo/FIFO_Memory_Formal/assets/133064673/0e7aa5b5-7f67-447c-8bcf-47d6ab10087e)

**Comment by TeresaReLo** [comment]
Hi, I already proved the fix that you provided, and it works, but just for the record, we add to the precondition of the assertion the flag so that way we ensure that the data is stable also after reset.

![5](https://github.com/TeresaReLo/FIFO_Memory_Formal/assets/133064673/0e7aa5b5-7f67-447c-8bcf-47d6ab10087e)
